const componentList = [
    {
        componentName: 'Компонент "Хедер"',
        task: 'WSADMIN-1',
        routeText: 'Виден сейчас)',
        routeLink: '',
    },
    {
        componentName: 'Компонент "Фильтр товаров"',
        task: 'WSADMIN-2',
        routeText: '/goodsFilter',
        routeLink: '/goodsFilter',
    },
    {
        componentName: 'Компонент "Список категорий"',
        task: 'WSADMIN-3',
        routeText: '/categories',
        routeLink: '/categories',
    },
    {
        componentName: 'Компонент "Статистика"',
        task: 'WSADMIN-4',
        routeText: 'Виден сейчас в хедере',
        routeLink: '',
    },
    {
        componentName: 'Компонент "Добавление категории"',
        task: 'WSADMIN-5',
        routeText: '/addCategory',
        routeLink: '/addCategory',
    },
    {
        componentName: 'Компонент "Атрибуты"',
        task: 'WSADMIN-6',
        routeText: '/attributeList',
        routeLink: '/attributeList',
    },
    {
        componentName: 'Компонент "Группы атрибутов"',
        task: 'WSADMIN-7',
        routeText: '/attributeGroup',
        routeLink: '/attributeGroup',
    },
    {
        componentName: 'Компонент "Список товаров"',
        task: 'WSADMIN-9',
        routeText: '/myGoodsList',
        routeLink: '/myGoodsList',
    },
    {
        componentName: 'Компонент "Купоны"',
        task: 'WSADMIN-17',
        routeText: '/couponsList',
        routeLink: '/couponsList',
    },
    {
        componentName: 'Компонент "Редактирование купонов"',
        task: 'WSADMIN-18',
        routeText: '/couponsList',
        routeLink: '/couponsList',
    },
    {
        componentName: 'Компонент "Редактирование товаров"',
        task: 'WSADMIN-11',
        routeText: '/editGood или по нажатию карандаша в /myGoodList',
        routeLink: '/editGood',
    },
    {
        componentName: 'Компонент "Хедер добавления товаров"',
        task: 'WSADMIN-33',
        routeText: '/goodAdd',
        routeLink: '/goodAdd',
    },
    {
        componentName: 'Компонент "Главное меню"',
        task: 'WSADMIN-70',
        routeText: 'Виден при нажатии на кнопке МЕНЮ',
        routeLink: '',
    },
    {
        componentName: 'Компонент №1 в форме "Новый заказ"',
        task: 'WSADMIN-82',
        routeText: '/orders/1',
        routeLink: '/orders/1',
    },
    {
        componentName: 'Компонент №3 в форме "Новый заказ"',
        task: 'WSADMIN-88',
        routeText: '/orders/1',
        routeLink: '/orders/1',
    },
    {
        componentName: 'Компонент №2 в форме "Новый заказ"',
        task: 'WSADMIN-86',
        routeText: '/orderInfo',
        routeLink: '/orderInfo',
    },
    {
        componentName: 'Страница "Товары"',
        task: 'WSADMIN-79',
        routeText: '/goods',
        routeLink: '/goods',
    },
    {
        componentName: 'Компонент "Страница пользователи"',
        task: 'WSADMIN-99',
        routeText: '/users',
        routeLink: '/users',
    },
    {
        componentName: 'Компонент "Страница НОВЫЙ ЗАКАЗ"',
        task: 'WSADMIN-87',
        routeText: '/new-order',
        routeLink: '/new-order',
    },
    {
        componentName: 'Компонент "Добавление клиента"',
        task: 'WSADMIN-75',
        routeText: '/clients/add',
        routeLink: '/clients/add',
    },
    {
        componentName: 'Кнопка "Экспорт"',
        task: 'WSADMIN-80',
        routeText: '/export',
        routeLink: '/export',
    },
    {
        componentName: 'Страница "Клиенты"',
        task: 'WSADMIN-76',
        routeText: '/clients/pages/1',
        routeLink: '/clients/pages/1',
    },
    {
        componentName: 'Дополнительные функции на странице "Клиенты"',
        task: 'WSADMIN-77',
        routeText: '/clients/pages/1',
        routeLink: '/clients/pages/1',
    },
    {
        componentName: 'Шапка/сортировка на странице "Клиенты"',
        task: 'WSADMIN-78',
        routeText: '/clients/pages/1',
        routeLink: '/clients/pages/1',
    },
    {
        componentName: 'Страница "Контакты"',
        task: 'WSADMIN-107',
        routeText: '/contacts',
        routeLink: '/contacts',
    },
    {
        componentName: 'Страница "Доставка"',
        task: 'WSADMIN-105',
        routeText: '/delivery',
        routeLink: '/delivery',
    },
    {
        componentName: 'Страница "Новая почта"',
        task: 'WSADMIN-122',
        routeText: '/np',
        routeLink: '/np',
    },
    {
        componentName: 'Страница "Последние заказы"',
        task: 'WSADMIN-63',
        routeText: '/lastorders',
        routeLink: '/lastorders',
    },
    {
        componentName: 'Страница "Оплаты"',
        task: 'WSADMIN-106',
        routeText: '/checkout',
        routeLink: '/checkout',
    },
    {
        componentName: 'Страница "Характеристики товара"',
        task: 'WSADMIN-128',
        routeText: '/characteristics',
        routeLink: '/characteristics',
    },
    {
        componentName: 'Страница "Добавление характеристики товара"',
        task: 'WSADMIN-128',
        routeText: '/addCharacteristic',
        routeLink: '/addCharacteristic',
    },
    {
        componentName: 'Страница "Группа характеристик товара"',
        task: 'WSADMIN-129',
        routeText: '/characteristicGroups',
        routeLink: '/characteristicGroups',
    },
    {
        componentName: 'Страница "Добавление группы характеристик товара"',
        task: 'WSADMIN-129',
        routeText: '/addCharacteristicGroup',
        routeLink: '/addCharacteristicGroup',
    },
    {
        componentName: 'Страница "Наборы характеристик товаров"',
        task: 'WSADMIN-132',
        routeText: '/characteristicSets',
        routeLink: '/characteristicSets',
    },
    {
        componentName: 'Страница "Добавление набора характеристик"',
        task: 'WSADMIN-132',
        routeText: '/addCharacteristicSet',
        routeLink: '/addCharacteristicSet',
    },
]

export default componentList
