export const MEGA_MENU_SUB_CONTAINER_TOP_BOTTOM_MARGIN = 50
export const COLUMN_WIDTH = 210
export const SUB_ITEM_HEIGHT = 33
export const SUB_ITEM_PADDING_BOTTOM = 15
export const SUB_SUB_ITEM_HEIGHT = 23
export const SUB_ITEMS_PADDING_LEFT = 34
