export const LOGIN_ROUTE = '/login'
export const MAIN_ROUTE = '/main'
export const GOOD_LIST_ROUTE = '/goodList'
export const GOOD_ADD_ROUTE = '/goodAdd'
export const GOOD_FILTER_ROUTE = '/goodFilter'
export const ADD_CATEGORY_ROUTE = '/addCategory'